<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>FinalPrice</name>
  <uuid>95ac9b84-5ff0-499e-8405-a0dc6fcea1be</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the Age of 'Client Info' is more than 12
then
	set decision to the Price of 'Product Info' * 'Promo Values' ;
else
set decision to the Price of 'Product Info';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
